version: '3'

tasks:
  run:
    desc: "Build and start the application"
    cmds:
      - docker-compose -f deploy/docker-compose.yaml up -d --build

  stop:
    desc: "Stop the application"
    cmds:
      - docker-compose -f deploy/docker-compose.yaml down

  unit-test:
    desc: "Run unit tests"
    cmds:
      - go test -v ./internal/...

  coverage-test:
    desc: "Get test coverage"
    cmds:
      - go test -coverprofile=coverage.out ./internal/...
      - go tool cover -func=coverage.out

  e2e-test:
    desc: "Run E2E tests"
    cmds:
      - CONFIG_PATH=../configs/local.yaml go test -v ./tests

  migrate-up:
    desc: "Apply all pending database migrations"
    cmds:
      - docker exec -it avito-shop-service /migrator up

  migrate-down:
    desc: "Rollback the last database migration"
    cmds:
      - docker exec -it avito-shop-service /migrator down

  migrate-create:
    desc: "Create a new migration (usage: task migrate-create name=<migration_name>)"
    cmds:
      - migrate create -ext sql -dir migrations -seq {{.name}}

